[package]
name = "localcanvas"
version = "0.1.0"
description = "A local-first Excalidraw library for macOS"
authors = ["Pratik Rai"]
edition = "2021"

[lib]
name = "localcanvas_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.40", features = ["bundled"] }
notify = "8"
plist = "1"
sha2 = "0.11"
xattr = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
uuid = { version = "1", features = ["v4"] }
walkdir = "2"
tauri-plugin-deep-link = "2.4.9"
